// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://binzsdvpbzbnspqgbnvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbnpzZHZwYnpibnNwcWdibnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDI1NjgsImV4cCI6MjA2OTM3ODU2OH0.kCs-ABG6hNoGZUnDiqfNZpYrbVL9H2t-lV7mA4OxaOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});